title = "Rustyx Configuration File"

[listener]
listen = "http://127.0.0.1:3000"

[servers]
servers = [
    { proxy_pass = "http://127.0.0.1:9000", path= "/v1/" },
    { proxy_pass = "http://127.0.0.1:9001", path= "/v2/" }
]
