[[server]]
listen = ["127.0.0.1:8000"]
name = "localhost"



[[server.location]]
path = "/api"
proxy_pass = "127.0.0.1:9001"


# static file
[[server.location]]
path = "/"
root = "/home/joel/Documents/Development/projects/Rustyx/static"
