
title = "Rustyx Configuration File"

[listener]
listen = "127.0.0.1:3000"

[servers]

[[servers.locations]]
path = "/v1/"
proxy_pass = "127.0.0.1:9000"

[[servers.locations]]
path = "/v2/"
proxy_pass = "127.0.0.1:9001"